name: atly
description: atly made with Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  google_fonts: ^4.0.3
  getwidget: ^3.0.1
  fluttericon: ^2.0.0
  flutter_signin_button: ^2.0.0
  persistent_bottom_nav_bar: ^5.0.2
  device_preview: ^1.1.0
  go_router: ^6.0.9
  flutter_firebase_chat_core: ^1.6.4
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_messaging: ^14.2.5
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  awesome_snackbar_content: ^0.1.1
  logger: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/backgrounds/
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  background_image: "assets/images/splash_screen_img.png"

  android_12:
    image: assets/icons/app_launcher_icon.png

  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_launcher_icon.png"
  min_sdk_android: 21
