// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK1laahQkak18BmydhRxLQ1aIdNbkbOyY',
    appId: '1:884754944274:web:f98b9514ac5bd13e5ae3cb',
    messagingSenderId: '884754944274',
    projectId: 'atly-98006',
    authDomain: 'atly-98006.firebaseapp.com',
    storageBucket: 'atly-98006.appspot.com',
    measurementId: 'G-44HBGRF0EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPIZZWNzoCaPViHm_d1TJHg0AoEH3V11k',
    appId: '1:884754944274:android:6aa0ca499e5d48945ae3cb',
    messagingSenderId: '884754944274',
    projectId: 'atly-98006',
    storageBucket: 'atly-98006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8uVRCQDIUYtLNoPTCpAZ6LYeX4yMJxvA',
    appId: '1:884754944274:ios:595ad4440ab5d80c5ae3cb',
    messagingSenderId: '884754944274',
    projectId: 'atly-98006',
    storageBucket: 'atly-98006.appspot.com',
    androidClientId: '884754944274-bldkn3bqrkemd00ej32gbliggvsn3hvg.apps.googleusercontent.com',
    iosClientId: '884754944274-2ismjhommv1lhe3frhl8i1gbag39k3bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.atly',
  );
}
